# Generated by Django 3.2 on 2022-05-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        # # migrations.RemoveField(
        # #     model_name='contact',
        # #     name='user_key',
        # ),
    ]
