# Generated by Django 3.2 on 2022-05-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_key',
            new_name='user',
        ),
    ]
