# Generated by Django 3.2 on 2022-06-15 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='contact',
        ),
        migrations.AddField(
            model_name='reserve',
            name='contact',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='parties',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
