# Generated by Django 3.2 on 2022-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220615_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='contact',
        ),
        migrations.AddField(
            model_name='reserve',
            name='contact',
            field=models.TextField(default=''),
        ),
    ]
