# Generated by Django 3.2 on 2022-06-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0005_reserve_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
