# Generated by Django 3.2 on 2022-06-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20220618_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
