# Generated by Django 3.2 on 2022-06-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reserve_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='contact',
        ),
    ]
