# Generated by Django 3.2 on 2022-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reserve_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
