# Generated by Django 3.2 on 2022-06-23 06:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_aboutus_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Index'),
        ),
    ]
