# Generated by Django 3.2 on 2022-06-23 06:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_index_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Index')),
            ],
        ),
        migrations.RemoveField(
            model_name='index',
            name='img',
        ),
    ]
