# Generated by Django 3.2 on 2022-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20220623_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimage',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
